# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f3682010c74774789e7213a7b537f4c353546b1d1bf99c1d91c22ad786f84d35dfdd1c04b40a037d3c446dc96c18b1ddfc40d9e60d5beac86bd7e26ea3f6cb7c

test:
  secret_key_base: 986d3d04fd21766b5dea9b82319614c5f8974c91f8b1cbf266088d9c024531b83342f98a41a5f6b4e3ce8552e9f5703c840a23000c7f21116d27c111d73dbf92

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
